search_365.settings:
  type: config_object
  label: 'Search 365 Settings'
  mapping:
    connection_info:
      type: mapping
      label: 'Connection info'
      mapping:
        baseurl:
          type: string
          label: 'Base URL'
        collection:
          type: string
          label: 'Collection'
    display_settings:
      type: mapping
      label: 'Display settings'
      mapping:
        drupal_path:
          type: string
          label: 'Drupal path'
        search_title:
          type: string
          label: 'Search title'
        page_size:
          type: integer
          label: 'Page size'
